services:
  videostreamparser:
    image: jpkitt/videostreamparser:latest
    environment:
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_NAME=${MONGODB_NAME}
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_started
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
volumes:
  mongodb_data: