services:
  videostreamsegments:
    image: jpkitt/videostreamsegments:latest
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_started
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # The standard AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672
    restart: unless-stopped
